### ISSUE TITLE
Status of the Project

### ISSUE THREAD

**Issue by chrisreedio** [podonoghue/DSOX_LAN#1]
I see that the README says work in progress but was wondering if this was ever tested to be working?

Thanks!

**Comment by podonoghue** [comment]
I have used it in a DSOX3034A DSO without any problems as a network interface.
I have not tried the serial interface as when I did this the DSO was under warranty and I didn't won't to open the box.  Lost interest in that part of it since then.
Make sure you can get the correct magnetics RJMG1-6312-81-01NR.  That one was one I had on hand so may not be the most common.

It would be useful to look here https://www.eevblog.com/forum/projects/lan-adapter-for-the-agilent-keysight-dso-x-3000-2000/ as well.
bye

**Comment by chrisreedio** [comment]
Thanks for the information! I'll check out that thread.
